name: OneShot

options:
  bundleIdPrefix: com.grantbirki
  deploymentTarget:
    macOS: "14.0"

targets:
  OneShot:
    type: application
    platform: macOS
    sources:
      - Sources
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: OneShot
        LSUIElement: true
        NSHighResolutionCapable: true
        NSScreenCaptureUsageDescription: OneShot needs screen recording access to capture screenshots.
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.grantbirki.oneshot
        MARKETING_VERSION: 0.0.0
        CURRENT_PROJECT_VERSION: 0.0.0
  OneShotTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - Tests
    dependencies:
      - target: OneShot
