name: OneShot

options:
  bundleIdPrefix: com.grantbirki
  deploymentTarget:
    macOS: "14.0"

targets:
  OneShot:
    type: application
    platform: macOS
    sources:
      - Sources
    resources:
      - Sources/Resources/shutter.wav
      - Sources/Resources/canon70d.wav
      - Sources/Resources/sony_a7ii.wav
      - Sources/Resources/pop-pop_canon_ae-1.wav
      - Sources/Resources/Assets.xcassets
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: $(APP_DISPLAY_NAME)
        CFBundleIconName: AppIcon
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        GIT_SHA: $(GIT_SHA)
        LSUIElement: true
        NSHighResolutionCapable: true
        NSScreenCaptureUsageDescription: OneShot needs screen recording access to capture screenshots.
    settings:
      base:
        APP_DISPLAY_NAME: OneShot
        PRODUCT_BUNDLE_IDENTIFIER: com.grantbirki.oneshot
        MARKETING_VERSION: 0.0.0
        CURRENT_PROJECT_VERSION: 0.0.0
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      configs:
        Debug:
          APP_DISPLAY_NAME: OneShot Dev
          PRODUCT_BUNDLE_IDENTIFIER: com.grantbirki.oneshot.dev
  OneShotTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - Tests
    dependencies:
      - target: OneShot
